name: fiap-env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/free
  - defaults
dependencies:
  - bokeh=1.3.4
  - boto=2.49.0
  - boto3=1.9.199
  - botocore=1.12.199
  - gensim=3.4.0
  - google-api-core=1.11.0
  - google-cloud-bigquery=1.10.0
  - imbalanced-learn=0.3.3
  - ipython=7.7.0
  - joblib=0.13.2
  - keras=2.2.4=0
  - lightgbm=2.2.1
  - matplotlib=3.1.0
  - nltk=3.4.4
  - notebook=6.0.0
  - numpy=1.16.4
  - pandas=0.25.0
  - pandas-datareader=0.7.0
  - patsy=0.5.1
  - pip=19.2.2
  - plotly=4.0.0
  - py-xgboost=0.90
  - python=3.6.9
  - python-cufflinks=0.14.5
  - python-graphviz=0.10.1
  - pygraphviz==1.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - shap=0.27.0
  - scikit-learn
  - spacy=2.0.16
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - tensorflow=1.5.0
  - tqdm=4.32.1
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz
    - language-check==1.1
    - pycontractions==2.0.0
    - python-utils==2.3.0
    - googledrivedownloader==0.4
